name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # Change to 'master' if your main branch is master

# Add this permissions block so the bot is allowed to write to the repository
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./clients  # This deploys your clients folder
